/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * FetchDock
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration?: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}


/**
 * DownloadJobApi - fetch parameter creator
 * @export
 */
export const DownloadJobApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJob resources.
         * @summary Retrieves the collection of DownloadJob resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/download_jobs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(options: any = {}): FetchArgs {
            const localVarPath = `/download_jobs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a DownloadJob resource.
         * @summary Retrieves a DownloadJob resource.
         * @param {any} uuid DownloadJob identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsUuidGet(uuid: any, options: any = {}): FetchArgs {
            // verify required parameter 'uuid' is not null or undefined
            if (uuid === null || uuid === undefined) {
                throw new RequiredError('uuid','Required parameter uuid was null or undefined when calling apiDownloadJobsUuidGet.');
            }
            const localVarPath = `/download_jobs/{uuid}`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadJobApi - functional programming interface
 * @export
 */
export const DownloadJobApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJob resources.
         * @summary Retrieves the collection of DownloadJob resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsGetCollection(page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsPost(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a DownloadJob resource.
         * @summary Retrieves a DownloadJob resource.
         * @param {any} uuid DownloadJob identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsUuidGet(uuid: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsUuidGet(uuid, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadJobApi - factory interface
 * @export
 */
export const DownloadJobApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of DownloadJob resources.
         * @summary Retrieves the collection of DownloadJob resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsGetCollection(page?: any, options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsPost(options)(fetch, basePath);
        },
        /**
         * Retrieves a DownloadJob resource.
         * @summary Retrieves a DownloadJob resource.
         * @param {any} uuid DownloadJob identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsUuidGet(uuid: any, options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsUuidGet(uuid, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadJobApi - object-oriented interface
 * @export
 * @class DownloadJobApi
 * @extends {BaseAPI}
 */
export class DownloadJobApi extends BaseAPI {
    /**
     * Retrieves the collection of DownloadJob resources.
     * @summary Retrieves the collection of DownloadJob resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobApi
     */
    public apiDownloadJobsGetCollection(page?: any, options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Creates a DownloadJob resource.
     * @summary Creates a DownloadJob resource.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobApi
     */
    public apiDownloadJobsPost(options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsPost(options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a DownloadJob resource.
     * @summary Retrieves a DownloadJob resource.
     * @param {any} uuid DownloadJob identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobApi
     */
    public apiDownloadJobsUuidGet(uuid: any, options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsUuidGet(uuid, options)(this.fetch, this.basePath);
    }

}

/**
 * DownloadJobEventApi - fetch parameter creator
 * @export
 */
export const DownloadJobEventApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            // verify required parameter 'downloadJobUuid' is not null or undefined
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid','Required parameter downloadJobUuid was null or undefined when calling apiDownloadJobsDownloadJobUuideventsFormatGetCollection.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/events`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadJobEventApi - functional programming interface
 * @export
 */
export const DownloadJobEventApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloadJobEventApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadJobEventApi - factory interface
 * @export
 */
export const DownloadJobEventApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadJobEventApiFp(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadJobEventApi - object-oriented interface
 * @export
 * @class DownloadJobEventApi
 * @extends {BaseAPI}
 */
export class DownloadJobEventApi extends BaseAPI {
    /**
     * Retrieves the collection of DownloadJobEvent resources.
     * @summary Retrieves the collection of DownloadJobEvent resources.
     * @param {any} downloadJobUuid DownloadJobEvent identifier
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobEventApi
     */
    public apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadJobEventApiFp(this.configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }

}

/**
 * DownloadedFileApi - fetch parameter creator
 * @export
 */
export const DownloadedFileApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            // verify required parameter 'downloadJobUuid' is not null or undefined
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid','Required parameter downloadJobUuid was null or undefined when calling apiDownloadJobsDownloadJobUuidfilesFormatGetCollection.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/files`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadedFileApi - functional programming interface
 * @export
 */
export const DownloadedFileApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloadedFileApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadedFileApi - factory interface
 * @export
 */
export const DownloadedFileApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadedFileApiFp(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadedFileApi - object-oriented interface
 * @export
 * @class DownloadedFileApi
 * @extends {BaseAPI}
 */
export class DownloadedFileApi extends BaseAPI {
    /**
     * Retrieves the collection of DownloadedFile resources.
     * @summary Retrieves the collection of DownloadedFile resources.
     * @param {any} downloadJobUuid DownloadedFile identifier
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadedFileApi
     */
    public apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadedFileApiFp(this.configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }

}

/**
 * DownloaderApi - fetch parameter creator
 * @export
 */
export const DownloaderApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/downloaders`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiDownloadersIdGet.');
            }
            const localVarPath = `/downloaders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloaderApi - functional programming interface
 * @export
 */
export const DownloaderApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloaderApiFetchParamCreator(configuration).apiDownloadersGetCollection(page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DownloaderApiFetchParamCreator(configuration).apiDownloadersIdGet(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloaderApi - factory interface
 * @export
 */
export const DownloaderApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * DownloaderApi - object-oriented interface
 * @export
 * @class DownloaderApi
 * @extends {BaseAPI}
 */
export class DownloaderApi extends BaseAPI {
    /**
     * Retrieves the collection of Downloader resources.
     * @summary Retrieves the collection of Downloader resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloaderApi
     */
    public apiDownloadersGetCollection(page?: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a Downloader resource.
     * @summary Retrieves a Downloader resource.
     * @param {any} id Downloader identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloaderApi
     */
    public apiDownloadersIdGet(id: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersIdGet(id, options)(this.fetch, this.basePath);
    }

}

/**
 * LoginCheckApi - fetch parameter creator
 * @export
 */
export const LoginCheckApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a user token.
         * @summary Creates a user token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginCheckPost(options: any = {}): FetchArgs {
            const localVarPath = `/api/login_check`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LoginCheckApi - functional programming interface
 * @export
 */
export const LoginCheckApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a user token.
         * @summary Creates a user token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginCheckPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LoginCheckApiFetchParamCreator(configuration).loginCheckPost(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * LoginCheckApi - factory interface
 * @export
 */
export const LoginCheckApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Creates a user token.
         * @summary Creates a user token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginCheckPost(options?: any) {
            return LoginCheckApiFp(configuration).loginCheckPost(options)(fetch, basePath);
        },
    };
};

/**
 * LoginCheckApi - object-oriented interface
 * @export
 * @class LoginCheckApi
 * @extends {BaseAPI}
 */
export class LoginCheckApi extends BaseAPI {
    /**
     * Creates a user token.
     * @summary Creates a user token.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoginCheckApi
     */
    public loginCheckPost(options?: any) {
        return LoginCheckApiFp(this.configuration).loginCheckPost(options)(this.fetch, this.basePath);
    }

}

/**
 * SupportedSiteApi - fetch parameter creator
 * @export
 */
export const SupportedSiteApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/supported_sites`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiSupportedSitesIdGet.');
            }
            const localVarPath = `/supported_sites/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SupportedSiteApi - functional programming interface
 * @export
 */
export const SupportedSiteApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesGetCollection(page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesIdGet(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * SupportedSiteApi - factory interface
 * @export
 */
export const SupportedSiteApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * SupportedSiteApi - object-oriented interface
 * @export
 * @class SupportedSiteApi
 * @extends {BaseAPI}
 */
export class SupportedSiteApi extends BaseAPI {
    /**
     * Retrieves the collection of SupportedSite resources.
     * @summary Retrieves the collection of SupportedSite resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportedSiteApi
     */
    public apiSupportedSitesGetCollection(page?: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a SupportedSite resource.
     * @summary Retrieves a SupportedSite resource.
     * @param {any} id SupportedSite identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportedSiteApi
     */
    public apiSupportedSitesIdGet(id: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesIdGet(id, options)(this.fetch, this.basePath);
    }

}

/**
 * VersionApi - fetch parameter creator
 * @export
 */
export const VersionApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/versions`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVersionsIdGet.');
            }
            const localVarPath = `/versions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VersionApi - functional programming interface
 * @export
 */
export const VersionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = VersionApiFetchParamCreator(configuration).apiVersionsGetCollection(page, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = VersionApiFetchParamCreator(configuration).apiVersionsIdGet(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * VersionApi - factory interface
 * @export
 */
export const VersionApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * VersionApi - object-oriented interface
 * @export
 * @class VersionApi
 * @extends {BaseAPI}
 */
export class VersionApi extends BaseAPI {
    /**
     * Retrieves the collection of Version resources.
     * @summary Retrieves the collection of Version resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionApi
     */
    public apiVersionsGetCollection(page?: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a Version resource.
     * @summary Retrieves a Version resource.
     * @param {any} id Version identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionApi
     */
    public apiVersionsIdGet(id: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsIdGet(id, options)(this.fetch, this.basePath);
    }

}

