/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Download Router
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * Unprocessable entity
 * @export
 * @interface ConstraintViolation
 */
export interface ConstraintViolation {
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    violations?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    detail?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    type?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    title?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolation
     */
    instance?: any;
}
/**
 * Unprocessable entity
 * @export
 * @interface ConstraintViolationJsonld
 */
export interface ConstraintViolationJsonld {
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    violations?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    detail?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    description?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    type?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    title?: any;
    /**
     * 
     * @type {any}
     * @memberof ConstraintViolationJsonld
     */
    instance?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobDownloadJobDTO
 */
export interface DownloadJobDownloadJobDTO {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobDownloadJobDTO
     */
    uri: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobDownloadJobDTO
     */
    userAgent?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobDownloadJobDTO
     */
    cookies?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobDownloadJobDTO
     */
    downloader?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobEvent
 */
export interface DownloadJobEvent {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    workerIdentifier?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    event?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    source?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    updateMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    context?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    metadata?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    exceptionMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    createdAt?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEvent
     */
    updatedAt?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobEventJsonld
 */
export interface DownloadJobEventJsonld {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    workerIdentifier?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    event?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    source?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    updateMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    context?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    metadata?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    exceptionMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    createdAt?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventJsonld
     */
    updatedAt?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobEventXml
 */
export interface DownloadJobEventXml {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    workerIdentifier?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    event?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    source?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    updateMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    context?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    metadata?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    exceptionMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    createdAt?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventXml
     */
    updatedAt?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobEventYaml
 */
export interface DownloadJobEventYaml {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    workerIdentifier?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    event?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    source?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    updateMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    context?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    metadata?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    exceptionMessage?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    createdAt?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobEventYaml
     */
    updatedAt?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobJobAcceptedDTO
 */
export interface DownloadJobJobAcceptedDTO {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTO
     */
    jobUuid?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTO
     */
    token?: any;
    /**
     * 
     * @type {JobTypeEnum}
     * @memberof DownloadJobJobAcceptedDTO
     */
    jobType?: JobTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTO
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTO
     */
    message?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobJobAcceptedDTOJsonld
 */
export interface DownloadJobJobAcceptedDTOJsonld {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOJsonld
     */
    jobUuid?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOJsonld
     */
    token?: any;
    /**
     * 
     * @type {JobTypeEnumJsonld}
     * @memberof DownloadJobJobAcceptedDTOJsonld
     */
    jobType?: JobTypeEnumJsonld;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOJsonld
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOJsonld
     */
    message?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobJobAcceptedDTOXml
 */
export interface DownloadJobJobAcceptedDTOXml {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOXml
     */
    jobUuid?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOXml
     */
    token?: any;
    /**
     * 
     * @type {JobTypeEnumXml}
     * @memberof DownloadJobJobAcceptedDTOXml
     */
    jobType?: JobTypeEnumXml;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOXml
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOXml
     */
    message?: any;
}
/**
 * 
 * @export
 * @interface DownloadJobJobAcceptedDTOYaml
 */
export interface DownloadJobJobAcceptedDTOYaml {
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOYaml
     */
    jobUuid?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOYaml
     */
    token?: any;
    /**
     * 
     * @type {JobTypeEnumYaml}
     * @memberof DownloadJobJobAcceptedDTOYaml
     */
    jobType?: JobTypeEnumYaml;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOYaml
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadJobJobAcceptedDTOYaml
     */
    message?: any;
}
/**
 * 
 * @export
 * @interface DownloadedFileDownloadedFileRead
 */
export interface DownloadedFileDownloadedFileRead {
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileDownloadedFileRead
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileDownloadedFileRead
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileDownloadedFileRead
     */
    visible?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileDownloadedFileRead
     */
    filename?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileDownloadedFileRead
     */
    downloadUri?: any;
}
/**
 * 
 * @export
 * @interface DownloadedFileJsonldDownloadedFileRead
 */
export interface DownloadedFileJsonldDownloadedFileRead {
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileJsonldDownloadedFileRead
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileJsonldDownloadedFileRead
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileJsonldDownloadedFileRead
     */
    visible?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileJsonldDownloadedFileRead
     */
    filename?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileJsonldDownloadedFileRead
     */
    downloadUri?: any;
}
/**
 * 
 * @export
 * @interface DownloadedFileXmlDownloadedFileRead
 */
export interface DownloadedFileXmlDownloadedFileRead {
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileXmlDownloadedFileRead
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileXmlDownloadedFileRead
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileXmlDownloadedFileRead
     */
    visible?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileXmlDownloadedFileRead
     */
    filename?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileXmlDownloadedFileRead
     */
    downloadUri?: any;
}
/**
 * 
 * @export
 * @interface DownloadedFileYamlDownloadedFileRead
 */
export interface DownloadedFileYamlDownloadedFileRead {
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileYamlDownloadedFileRead
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileYamlDownloadedFileRead
     */
    downloadJob?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileYamlDownloadedFileRead
     */
    visible?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileYamlDownloadedFileRead
     */
    filename?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloadedFileYamlDownloadedFileRead
     */
    downloadUri?: any;
}
/**
 * 
 * @export
 * @interface Downloader
 */
export interface Downloader {
    /**
     * 
     * @type {any}
     * @memberof Downloader
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof Downloader
     */
    enabled?: any;
    /**
     * 
     * @type {DownloaderTypeEnum}
     * @memberof Downloader
     */
    downloaderType?: DownloaderTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof Downloader
     */
    supportedDomains?: any;
}
/**
 * 
 * @export
 * @interface DownloaderJsonld
 */
export interface DownloaderJsonld {
    /**
     * 
     * @type {any}
     * @memberof DownloaderJsonld
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloaderJsonld
     */
    enabled?: any;
    /**
     * 
     * @type {DownloaderTypeEnumJsonld}
     * @memberof DownloaderJsonld
     */
    downloaderType?: DownloaderTypeEnumJsonld;
    /**
     * 
     * @type {any}
     * @memberof DownloaderJsonld
     */
    supportedDomains?: any;
}
/**
 * 
 * @export
 * @interface DownloaderTypeEnum
 */
export interface DownloaderTypeEnum {
    /**
     * 
     * @type {any}
     * @memberof DownloaderTypeEnum
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface DownloaderTypeEnumJsonld
 */
export interface DownloaderTypeEnumJsonld {
    /**
     * 
     * @type {any}
     * @memberof DownloaderTypeEnumJsonld
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface DownloaderTypeEnumXml
 */
export interface DownloaderTypeEnumXml {
    /**
     * 
     * @type {any}
     * @memberof DownloaderTypeEnumXml
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface DownloaderTypeEnumYaml
 */
export interface DownloaderTypeEnumYaml {
    /**
     * 
     * @type {any}
     * @memberof DownloaderTypeEnumYaml
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface DownloaderXml
 */
export interface DownloaderXml {
    /**
     * 
     * @type {any}
     * @memberof DownloaderXml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloaderXml
     */
    enabled?: any;
    /**
     * 
     * @type {DownloaderTypeEnumXml}
     * @memberof DownloaderXml
     */
    downloaderType?: DownloaderTypeEnumXml;
    /**
     * 
     * @type {any}
     * @memberof DownloaderXml
     */
    supportedDomains?: any;
}
/**
 * 
 * @export
 * @interface DownloaderYaml
 */
export interface DownloaderYaml {
    /**
     * 
     * @type {any}
     * @memberof DownloaderYaml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof DownloaderYaml
     */
    enabled?: any;
    /**
     * 
     * @type {DownloaderTypeEnumYaml}
     * @memberof DownloaderYaml
     */
    downloaderType?: DownloaderTypeEnumYaml;
    /**
     * 
     * @type {any}
     * @memberof DownloaderYaml
     */
    supportedDomains?: any;
}
/**
 * A representation of common errors.
 * @export
 * @interface ErrorJsonld
 */
export interface ErrorJsonld {
    /**
     * A short, human-readable summary of the problem.
     * @type {any}
     * @memberof ErrorJsonld
     */
    title?: any;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {any}
     * @memberof ErrorJsonld
     */
    detail?: any;
    /**
     * 
     * @type {any}
     * @memberof ErrorJsonld
     */
    status?: any;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {any}
     * @memberof ErrorJsonld
     */
    instance?: any;
    /**
     * A URI reference that identifies the problem type
     * @type {any}
     * @memberof ErrorJsonld
     */
    type?: any;
    /**
     * 
     * @type {any}
     * @memberof ErrorJsonld
     */
    description?: any;
}
/**
 * 
 * @export
 */
export type HydraCollectionBaseSchema = any
/**
 * 
 * @export
 * @interface HydraCollectionBaseSchemaNoPagination
 */
export interface HydraCollectionBaseSchemaNoPagination {
    /**
     * 
     * @type {any}
     * @memberof HydraCollectionBaseSchemaNoPagination
     */
    totalItems?: any;
    /**
     * 
     * @type {HydraCollectionBaseSchemaNoPaginationSearch}
     * @memberof HydraCollectionBaseSchemaNoPagination
     */
    search?: HydraCollectionBaseSchemaNoPaginationSearch;
}
/**
 * 
 * @export
 * @interface HydraCollectionBaseSchemaNoPaginationSearch
 */
export interface HydraCollectionBaseSchemaNoPaginationSearch {
    /**
     * 
     * @type {any}
     * @memberof HydraCollectionBaseSchemaNoPaginationSearch
     */
    type?: any;
    /**
     * 
     * @type {any}
     * @memberof HydraCollectionBaseSchemaNoPaginationSearch
     */
    template?: any;
    /**
     * 
     * @type {any}
     * @memberof HydraCollectionBaseSchemaNoPaginationSearch
     */
    variableRepresentation?: any;
    /**
     * 
     * @type {any}
     * @memberof HydraCollectionBaseSchemaNoPaginationSearch
     */
    mapping?: any;
}
/**
 * 
 * @export
 * @interface JobTypeEnum
 */
export interface JobTypeEnum {
    /**
     * 
     * @type {any}
     * @memberof JobTypeEnum
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface JobTypeEnumJsonld
 */
export interface JobTypeEnumJsonld {
    /**
     * 
     * @type {any}
     * @memberof JobTypeEnumJsonld
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface JobTypeEnumXml
 */
export interface JobTypeEnumXml {
    /**
     * 
     * @type {any}
     * @memberof JobTypeEnumXml
     */
    name?: any;
}
/**
 * 
 * @export
 * @interface JobTypeEnumYaml
 */
export interface JobTypeEnumYaml {
    /**
     * 
     * @type {any}
     * @memberof JobTypeEnumYaml
     */
    name?: any;
}
/**
 * A representation of common errors.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * A short, human-readable summary of the problem.
     * @type {any}
     * @memberof ModelError
     */
    title?: any;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {any}
     * @memberof ModelError
     */
    detail?: any;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    status?: any;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {any}
     * @memberof ModelError
     */
    instance?: any;
    /**
     * A URI reference that identifies the problem type
     * @type {any}
     * @memberof ModelError
     */
    type?: any;
}
/**
 * 
 * @export
 * @interface SupportedSite
 */
export interface SupportedSite {
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    name?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    description?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    domains?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    enabled?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSite
     */
    metadata?: any;
}
/**
 * 
 * @export
 * @interface SupportedSiteJsonld
 */
export interface SupportedSiteJsonld {
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    name?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    description?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    domains?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    enabled?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteJsonld
     */
    metadata?: any;
}
/**
 * 
 * @export
 * @interface SupportedSiteXml
 */
export interface SupportedSiteXml {
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    name?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    description?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    domains?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    enabled?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteXml
     */
    metadata?: any;
}
/**
 * 
 * @export
 * @interface SupportedSiteYaml
 */
export interface SupportedSiteYaml {
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    name?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    description?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    domains?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    enabled?: any;
    /**
     * 
     * @type {any}
     * @memberof SupportedSiteYaml
     */
    metadata?: any;
}
/**
 * 
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * 
     * @type {any}
     * @memberof Version
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof Version
     */
    version?: any;
    /**
     * 
     * @type {any}
     * @memberof Version
     */
    currentVersion?: any;
    /**
     * 
     * @type {any}
     * @memberof Version
     */
    latestVersion?: any;
}
/**
 * 
 * @export
 * @interface VersionJsonld
 */
export interface VersionJsonld {
    /**
     * 
     * @type {any}
     * @memberof VersionJsonld
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionJsonld
     */
    version?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionJsonld
     */
    currentVersion?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionJsonld
     */
    latestVersion?: any;
}
/**
 * 
 * @export
 * @interface VersionXml
 */
export interface VersionXml {
    /**
     * 
     * @type {any}
     * @memberof VersionXml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionXml
     */
    version?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionXml
     */
    currentVersion?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionXml
     */
    latestVersion?: any;
}
/**
 * 
 * @export
 * @interface VersionYaml
 */
export interface VersionYaml {
    /**
     * 
     * @type {any}
     * @memberof VersionYaml
     */
    id?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionYaml
     */
    version?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionYaml
     */
    currentVersion?: any;
    /**
     * 
     * @type {any}
     * @memberof VersionYaml
     */
    latestVersion?: any;
}
/**
 * DownloadJobApi - fetch parameter creator
 * @export
 */
export const DownloadJobApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {DownloadJobDownloadJobDTO} body The new DownloadJob resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(body: DownloadJobDownloadJobDTO, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling apiDownloadJobsPost.');
            }
            const localVarPath = `/download_jobs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"DownloadJobDownloadJobDTO" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadJobApi - functional programming interface
 * @export
 */
export const DownloadJobApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {DownloadJobDownloadJobDTO} body The new DownloadJob resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(body: DownloadJobDownloadJobDTO, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DownloadJobJobAcceptedDTOJsonld> {
            const localVarFetchArgs = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadJobApi - factory interface
 * @export
 */
export const DownloadJobApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Creates a DownloadJob resource.
         * @summary Creates a DownloadJob resource.
         * @param {DownloadJobDownloadJobDTO} body The new DownloadJob resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsPost(body: DownloadJobDownloadJobDTO, options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsPost(body, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadJobApi - object-oriented interface
 * @export
 * @class DownloadJobApi
 * @extends {BaseAPI}
 */
export class DownloadJobApi extends BaseAPI {
    /**
     * Creates a DownloadJob resource.
     * @summary Creates a DownloadJob resource.
     * @param {DownloadJobDownloadJobDTO} body The new DownloadJob resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobApi
     */
    public apiDownloadJobsPost(body: DownloadJobDownloadJobDTO, options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsPost(body, options)(this.fetch, this.basePath);
    }

}
/**
 * DownloadJobEventApi - fetch parameter creator
 * @export
 */
export const DownloadJobEventApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            // verify required parameter 'downloadJobUuid' is not null or undefined
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid','Required parameter downloadJobUuid was null or undefined when calling apiDownloadJobsDownloadJobUuideventsFormatGetCollection.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/events`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadJobEventApi - functional programming interface
 * @export
 */
export const DownloadJobEventApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DownloadJobEventApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadJobEventApi - factory interface
 * @export
 */
export const DownloadJobEventApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of DownloadJobEvent resources.
         * @summary Retrieves the collection of DownloadJobEvent resources.
         * @param {any} downloadJobUuid DownloadJobEvent identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadJobEventApiFp(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadJobEventApi - object-oriented interface
 * @export
 * @class DownloadJobEventApi
 * @extends {BaseAPI}
 */
export class DownloadJobEventApi extends BaseAPI {
    /**
     * Retrieves the collection of DownloadJobEvent resources.
     * @summary Retrieves the collection of DownloadJobEvent resources.
     * @param {any} downloadJobUuid DownloadJobEvent identifier
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadJobEventApi
     */
    public apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadJobEventApiFp(this.configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }

}
/**
 * DownloadedFileApi - fetch parameter creator
 * @export
 */
export const DownloadedFileApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            // verify required parameter 'downloadJobUuid' is not null or undefined
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid','Required parameter downloadJobUuid was null or undefined when calling apiDownloadJobsDownloadJobUuidfilesFormatGetCollection.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/files`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloadedFileApi - functional programming interface
 * @export
 */
export const DownloadedFileApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DownloadedFileApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloadedFileApi - factory interface
 * @export
 */
export const DownloadedFileApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of DownloadedFile resources.
         * @summary Retrieves the collection of DownloadedFile resources.
         * @param {any} downloadJobUuid DownloadedFile identifier
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadedFileApiFp(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

/**
 * DownloadedFileApi - object-oriented interface
 * @export
 * @class DownloadedFileApi
 * @extends {BaseAPI}
 */
export class DownloadedFileApi extends BaseAPI {
    /**
     * Retrieves the collection of DownloadedFile resources.
     * @summary Retrieves the collection of DownloadedFile resources.
     * @param {any} downloadJobUuid DownloadedFile identifier
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadedFileApi
     */
    public apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadedFileApiFp(this.configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }

}
/**
 * DownloaderApi - fetch parameter creator
 * @export
 */
export const DownloaderApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/downloaders`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiDownloadersIdGet.');
            }
            const localVarPath = `/downloaders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DownloaderApi - functional programming interface
 * @export
 */
export const DownloaderApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DownloaderApiFetchParamCreator(configuration).apiDownloadersGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DownloaderJsonld> {
            const localVarFetchArgs = DownloaderApiFetchParamCreator(configuration).apiDownloadersIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DownloaderApi - factory interface
 * @export
 */
export const DownloaderApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of Downloader resources.
         * @summary Retrieves the collection of Downloader resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersGetCollection(page?: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a Downloader resource.
         * @summary Retrieves a Downloader resource.
         * @param {any} id Downloader identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadersIdGet(id: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * DownloaderApi - object-oriented interface
 * @export
 * @class DownloaderApi
 * @extends {BaseAPI}
 */
export class DownloaderApi extends BaseAPI {
    /**
     * Retrieves the collection of Downloader resources.
     * @summary Retrieves the collection of Downloader resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloaderApi
     */
    public apiDownloadersGetCollection(page?: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a Downloader resource.
     * @summary Retrieves a Downloader resource.
     * @param {any} id Downloader identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloaderApi
     */
    public apiDownloadersIdGet(id: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersIdGet(id, options)(this.fetch, this.basePath);
    }

}
/**
 * SupportedSiteApi - fetch parameter creator
 * @export
 */
export const SupportedSiteApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/supported_sites`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiSupportedSitesIdGet.');
            }
            const localVarPath = `/supported_sites/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SupportedSiteApi - functional programming interface
 * @export
 */
export const SupportedSiteApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<SupportedSiteJsonld> {
            const localVarFetchArgs = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * SupportedSiteApi - factory interface
 * @export
 */
export const SupportedSiteApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of SupportedSite resources.
         * @summary Retrieves the collection of SupportedSite resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesGetCollection(page?: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a SupportedSite resource.
         * @summary Retrieves a SupportedSite resource.
         * @param {any} id SupportedSite identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSupportedSitesIdGet(id: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * SupportedSiteApi - object-oriented interface
 * @export
 * @class SupportedSiteApi
 * @extends {BaseAPI}
 */
export class SupportedSiteApi extends BaseAPI {
    /**
     * Retrieves the collection of SupportedSite resources.
     * @summary Retrieves the collection of SupportedSite resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportedSiteApi
     */
    public apiSupportedSitesGetCollection(page?: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a SupportedSite resource.
     * @summary Retrieves a SupportedSite resource.
     * @param {any} id SupportedSite identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SupportedSiteApi
     */
    public apiSupportedSitesIdGet(id: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesIdGet(id, options)(this.fetch, this.basePath);
    }

}
/**
 * VersionApi - fetch parameter creator
 * @export
 */
export const VersionApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/versions`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVersionsIdGet.');
            }
            const localVarPath = `/versions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VersionApi - functional programming interface
 * @export
 */
export const VersionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = VersionApiFetchParamCreator(configuration).apiVersionsGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<VersionJsonld> {
            const localVarFetchArgs = VersionApiFetchParamCreator(configuration).apiVersionsIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * VersionApi - factory interface
 * @export
 */
export const VersionApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Retrieves the collection of Version resources.
         * @summary Retrieves the collection of Version resources.
         * @param {any} [page] The collection page number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsGetCollection(page?: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsGetCollection(page, options)(fetch, basePath);
        },
        /**
         * Retrieves a Version resource.
         * @summary Retrieves a Version resource.
         * @param {any} id Version identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVersionsIdGet(id: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsIdGet(id, options)(fetch, basePath);
        },
    };
};

/**
 * VersionApi - object-oriented interface
 * @export
 * @class VersionApi
 * @extends {BaseAPI}
 */
export class VersionApi extends BaseAPI {
    /**
     * Retrieves the collection of Version resources.
     * @summary Retrieves the collection of Version resources.
     * @param {any} [page] The collection page number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionApi
     */
    public apiVersionsGetCollection(page?: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsGetCollection(page, options)(this.fetch, this.basePath);
    }

    /**
     * Retrieves a Version resource.
     * @summary Retrieves a Version resource.
     * @param {any} id Version identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VersionApi
     */
    public apiVersionsIdGet(id: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsIdGet(id, options)(this.fetch, this.basePath);
    }

}
