/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Download Router
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

export interface FetchArgs {
    url: string;
    options: any;
}

export class BaseAPI {
    protected configuration?: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

export class RequiredError extends Error {
    name = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

// ---------------------------------------------------------------------------
// DownloadJobApi
// ---------------------------------------------------------------------------

export const DownloadJobApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiDownloadJobsGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/download_jobs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
        apiDownloadJobsPost(options: any = {}): FetchArgs {
            const localVarPath = `/download_jobs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
        apiDownloadJobsUuidGet(uuid: any, options: any = {}): FetchArgs {
            if (uuid === null || uuid === undefined) {
                throw new RequiredError('uuid', 'Required parameter uuid was null or undefined when calling apiDownloadJobsUuidGet.');
            }
            const localVarPath = `/download_jobs/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const DownloadJobApiFp = function (configuration?: Configuration) {
    return {
        apiDownloadJobsGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
        apiDownloadJobsPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsPost(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
        apiDownloadJobsUuidGet(uuid: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloadJobApiFetchParamCreator(configuration).apiDownloadJobsUuidGet(uuid, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const DownloadJobApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiDownloadJobsGetCollection(page?: any, options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsGetCollection(page, options)(fetch, basePath);
        },
        apiDownloadJobsPost(options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsPost(options)(fetch, basePath);
        },
        apiDownloadJobsUuidGet(uuid: any, options?: any) {
            return DownloadJobApiFp(configuration).apiDownloadJobsUuidGet(uuid, options)(fetch, basePath);
        },
    };
};

export class DownloadJobApi extends BaseAPI {
    public apiDownloadJobsGetCollection(page?: any, options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsGetCollection(page, options)(this.fetch, this.basePath);
    }
    public apiDownloadJobsPost(options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsPost(options)(this.fetch, this.basePath);
    }
    public apiDownloadJobsUuidGet(uuid: any, options?: any) {
        return DownloadJobApiFp(this.configuration).apiDownloadJobsUuidGet(uuid, options)(this.fetch, this.basePath);
    }
    /** Fetches the well-known browser-extension config from {basePath}/.well-known/browser-extension */
    public testServer(options?: any) {
        return fetch(this.basePath + '/.well-known/browser-extension', options)
            .then(async response => {
                if (response.ok) {
                    const responseJson = await response.json();
                    if (!responseJson.version || !responseJson.auth_mode) {
                        throw new Error('Invalid response format');
                    }
                    return {
                        success: true,
                        version: responseJson.version,
                        authMode: responseJson.auth_mode,
                        oauth2: responseJson.oauth2 ?? null,
                    };
                }
                throw new Error('Server is not running');
            })
            .catch(error => {
                console.error('Error fetching server info:', error);
                throw new Error('Server is not running');
            });
    }
}

// ---------------------------------------------------------------------------
// DownloadJobEventApi
// ---------------------------------------------------------------------------

export const DownloadJobEventApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid', 'Required parameter downloadJobUuid was null or undefined.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/events`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const DownloadJobEventApiFp = function (configuration?: Configuration) {
    return {
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloadJobEventApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const DownloadJobEventApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadJobEventApiFp(configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

export class DownloadJobEventApi extends BaseAPI {
    public apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadJobEventApiFp(this.configuration).apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }
}

// ---------------------------------------------------------------------------
// DownloadedFileApi
// ---------------------------------------------------------------------------

export const DownloadedFileApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options: any = {}): FetchArgs {
            if (downloadJobUuid === null || downloadJobUuid === undefined) {
                throw new RequiredError('downloadJobUuid', 'Required parameter downloadJobUuid was null or undefined.');
            }
            const localVarPath = `/download_jobs/{downloadJobUuid}/files`
                .replace(`{${"downloadJobUuid"}}`, encodeURIComponent(String(downloadJobUuid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const DownloadedFileApiFp = function (configuration?: Configuration) {
    return {
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloadedFileApiFetchParamCreator(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const DownloadedFileApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
            return DownloadedFileApiFp(configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(fetch, basePath);
        },
    };
};

export class DownloadedFileApi extends BaseAPI {
    public apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid: any, page?: any, options?: any) {
        return DownloadedFileApiFp(this.configuration).apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, options)(this.fetch, this.basePath);
    }
}

// ---------------------------------------------------------------------------
// DownloaderApi
// ---------------------------------------------------------------------------

export const DownloaderApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiDownloadersGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/downloaders`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
        apiDownloadersIdGet(id: any, options: any = {}): FetchArgs {
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiDownloadersIdGet.');
            }
            const localVarPath = `/downloaders/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const DownloaderApiFp = function (configuration?: Configuration) {
    return {
        apiDownloadersGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloaderApiFetchParamCreator(configuration).apiDownloadersGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
        apiDownloadersIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = DownloaderApiFetchParamCreator(configuration).apiDownloadersIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const DownloaderApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiDownloadersGetCollection(page?: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersGetCollection(page, options)(fetch, basePath);
        },
        apiDownloadersIdGet(id: any, options?: any) {
            return DownloaderApiFp(configuration).apiDownloadersIdGet(id, options)(fetch, basePath);
        },
    };
};

export class DownloaderApi extends BaseAPI {
    public apiDownloadersGetCollection(page?: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersGetCollection(page, options)(this.fetch, this.basePath);
    }
    public apiDownloadersIdGet(id: any, options?: any) {
        return DownloaderApiFp(this.configuration).apiDownloadersIdGet(id, options)(this.fetch, this.basePath);
    }
}

// ---------------------------------------------------------------------------
// LoginCheckApi
// ---------------------------------------------------------------------------

export const LoginCheckApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        loginCheckPost(options: any = {}): FetchArgs {
            const localVarPath = `/api/login_check`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const LoginCheckApiFp = function (configuration?: Configuration) {
    return {
        loginCheckPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = LoginCheckApiFetchParamCreator(configuration).loginCheckPost(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const LoginCheckApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        loginCheckPost(options?: any) {
            return LoginCheckApiFp(configuration).loginCheckPost(options)(fetch, basePath);
        },
    };
};

export class LoginCheckApi extends BaseAPI {
    public loginCheckPost(options?: any) {
        return LoginCheckApiFp(this.configuration).loginCheckPost(options)(this.fetch, this.basePath);
    }
}

// ---------------------------------------------------------------------------
// SupportedSiteApi
// ---------------------------------------------------------------------------

export const SupportedSiteApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiSupportedSitesGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/supported_sites`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
        apiSupportedSitesIdGet(id: any, options: any = {}): FetchArgs {
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiSupportedSitesIdGet.');
            }
            const localVarPath = `/supported_sites/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const SupportedSiteApiFp = function (configuration?: Configuration) {
    return {
        apiSupportedSitesGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
        apiSupportedSitesIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = SupportedSiteApiFetchParamCreator(configuration).apiSupportedSitesIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const SupportedSiteApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiSupportedSitesGetCollection(page?: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesGetCollection(page, options)(fetch, basePath);
        },
        apiSupportedSitesIdGet(id: any, options?: any) {
            return SupportedSiteApiFp(configuration).apiSupportedSitesIdGet(id, options)(fetch, basePath);
        },
    };
};

export class SupportedSiteApi extends BaseAPI {
    public apiSupportedSitesGetCollection(page?: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesGetCollection(page, options)(this.fetch, this.basePath);
    }
    public apiSupportedSitesIdGet(id: any, options?: any) {
        return SupportedSiteApiFp(this.configuration).apiSupportedSitesIdGet(id, options)(this.fetch, this.basePath);
    }
}

// ---------------------------------------------------------------------------
// VersionApi
// ---------------------------------------------------------------------------

export const VersionApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        apiVersionsGetCollection(page?: any, options: any = {}): FetchArgs {
            const localVarPath = `/versions`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            if (page !== undefined) localVarQueryParameter['page'] = page;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
        apiVersionsIdGet(id: any, options: any = {}): FetchArgs {
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiVersionsIdGet.');
            }
            const localVarPath = `/versions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return { url: url.format(localVarUrlObj), options: localVarRequestOptions };
        },
    };
};

export const VersionApiFp = function (configuration?: Configuration) {
    return {
        apiVersionsGetCollection(page?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = VersionApiFetchParamCreator(configuration).apiVersionsGetCollection(page, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
        apiVersionsIdGet(id: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const args = VersionApiFetchParamCreator(configuration).apiVersionsIdGet(id, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) =>
                fetch(basePath + args.url, args.options).then(r => { if (r.status >= 200 && r.status < 300) return r; throw r; });
        },
    };
};

export const VersionApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        apiVersionsGetCollection(page?: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsGetCollection(page, options)(fetch, basePath);
        },
        apiVersionsIdGet(id: any, options?: any) {
            return VersionApiFp(configuration).apiVersionsIdGet(id, options)(fetch, basePath);
        },
    };
};

export class VersionApi extends BaseAPI {
    public apiVersionsGetCollection(page?: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsGetCollection(page, options)(this.fetch, this.basePath);
    }
    public apiVersionsIdGet(id: any, options?: any) {
        return VersionApiFp(this.configuration).apiVersionsIdGet(id, options)(this.fetch, this.basePath);
    }

}
