/**
 * Download Router
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DownloadJobApi", () => {
  let instance: api.DownloadJobApi
  beforeEach(function() {
    instance = new api.DownloadJobApi(config)
  });

  test("apiDownloadJobsPost", () => {
    const body: api.DownloadJobDownloadJobDTO = {
      uri: 'test-uri'
    }
    return expect(instance.apiDownloadJobsPost(body, {})).resolves.toBe(null)
  })
})

describe("DownloadJobEventApi", () => {
  let instance: api.DownloadJobEventApi
  beforeEach(function() {
    instance = new api.DownloadJobEventApi(config)
  });

  test("apiDownloadJobsDownloadJobUuideventsFormatGetCollection", () => {
    const downloadJobUuid: any = undefined
    const page: any = undefined
    return expect(instance.apiDownloadJobsDownloadJobUuideventsFormatGetCollection(downloadJobUuid, page, {})).resolves.toBe(null)
  })
})

describe("DownloadedFileApi", () => {
  let instance: api.DownloadedFileApi
  beforeEach(function() {
    instance = new api.DownloadedFileApi(config)
  });

  test("apiDownloadJobsDownloadJobUuidfilesFormatGetCollection", () => {
    const downloadJobUuid: any = undefined
    const page: any = undefined
    return expect(instance.apiDownloadJobsDownloadJobUuidfilesFormatGetCollection(downloadJobUuid, page, {})).resolves.toBe(null)
  })
})

describe("DownloaderApi", () => {
  let instance: api.DownloaderApi
  beforeEach(function() {
    instance = new api.DownloaderApi(config)
  });

  test("apiDownloadersGetCollection", () => {
    const page: any = undefined
    return expect(instance.apiDownloadersGetCollection(page, {})).resolves.toBe(null)
  })
  test("apiDownloadersIdGet", () => {
    const id: any = undefined
    return expect(instance.apiDownloadersIdGet(id, {})).resolves.toBe(null)
  })
})

describe("SupportedSiteApi", () => {
  let instance: api.SupportedSiteApi
  beforeEach(function() {
    instance = new api.SupportedSiteApi(config)
  });

  test("apiSupportedSitesGetCollection", () => {
    const page: any = undefined
    return expect(instance.apiSupportedSitesGetCollection(page, {})).resolves.toBe(null)
  })
  test("apiSupportedSitesIdGet", () => {
    const id: any = undefined
    return expect(instance.apiSupportedSitesIdGet(id, {})).resolves.toBe(null)
  })
})

describe("VersionApi", () => {
  let instance: api.VersionApi
  beforeEach(function() {
    instance = new api.VersionApi(config)
  });

  test("apiVersionsGetCollection", () => {
    const page: any = undefined
    return expect(instance.apiVersionsGetCollection(page, {})).resolves.toBe(null)
  })
  test("apiVersionsIdGet", () => {
    const id: any = undefined
    return expect(instance.apiVersionsIdGet(id, {})).resolves.toBe(null)
  })
})

